### ISSUE TITLE
High CPU/memory usage possibly causing dropped blocks

### ISSUE THREAD

**Issue by Loo399** [Cardinal-Cryptography/aleph-node-issues#2]
### Did you read the documentation and guides?

- [X] I have inspected the documentation.

### Is there an existing issue?

- [X] I have searched the existing issues.

### Description of the problem

Validator will suddenly stop requiring server/container reboot ?due to surges in CPU/RAM usage.
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/129190487/229298722-d6ac66d9-f216-4fcb-baea-6eab9eeea974.png">

No obvious cause found in logs. (First crash - the first large spike in the CPU utilization graph)
[logs.txt](https://github.com/Cardinal-Cryptography/aleph-node-issues/files/11129926/logs.txt)
You can see when the server was rebooted.

Second crash a few hours later.
[logs_2.txt](https://github.com/Cardinal-Cryptography/aleph-node-issues/files/11129945/logs_2.txt)

### Information on your setup.

1. Running on Mainnet
2. version 0.10.0+mainnet-1023252c22e 
3. Validator node run using aleph-node-runner
4. (run with aleph-node-runner)
5. Ubuntu 22.04.1 LTS

### Did you attach relevant logs?

- [X] I have attached logs (if relevant).

**Comment by Loo399** [comment]
Thank you for your reply.  Running c5.xlarge on AWS gp2 1024 GiB 4vCPUs, Ubuntu

**Comment by Marcin-Radecki** [comment]
Hi, the `c5.xlarge` is not sufficient anymore for `aleph-node` version `0.10.0+mainnet-1023252c22e`. This version requires at least 8 GB to operate, e.g. `c5.2xlarge`. 

We'll update our hardware requirements to match that. Thanks for reporting and let us know whether this solved the issue.

**Comment by Loo399** [comment]
I double checked and c5.xlarge does have 8 GiB of memory.  c5.2xlarge starts at 16 GiB.  So far haven't had any further issues especially since adding [this substrate block watcher script](https://gist.github.com/Sekoya-Labs/4916d2d2b7aba0301ff21be47155531d).

**Comment by Marcin-Radecki** [comment]
Sorry, I mean we need 16 GB now, you're right c5.xlarge has 8 GB. If you run again with the problem of spikes in RAM we suggest upgrading to c5.2xlarge or c6i.2xlarge.

**Comment by Marcin-Radecki** [comment]
Hi, we've updated our spec reqs page: https://docs.alephzero.org/aleph-zero/validate/hardware-requirements
