### ISSUE TITLE
Issues after node migration

### ISSUE THREAD

**Issue by SlaVaAb** [Cardinal-Cryptography/aleph-node-issues#5]
### Did you read the documentation and guides?

- [ ] I have inspected the documentation.

### Is there an existing issue?

- [ ] I have searched the existing issues.

### Description of the problem

I moved the node to a new server. Everything worked well for about 2 hours and then an error appeared

### Information on your setup.

1.  Testnet
2.  0.10.1
3.  Docker

5. Ubuntu 22.04
6. CPU: AMD EPYC 7282 16-Core
    RAM:16
    SSD:1.6 TB

### Steps to reproduce

![2023-04-11_15_35_06-Window](https://user-images.githubusercontent.com/110197947/231501448-02755c8b-272a-46ce-a99a-8174240cb8a0.png)

### Did you attach relevant logs?

- [X] I have attached logs (if relevant).

**Comment by DamianStraszak** [comment]
This error suggests that the session keys disappeared from your disk while the node was running. Did you by accident edit or remove any files in the `keystore` directory? 

To fix, first of all restart the node. Then regenerate session keys and set them on chain, as explained here https://docs.alephzero.org/aleph-zero/validate/making-the-node-validate#generate-session-keys
